server:
  port: 8090
spring:
  mongodb:
    uri: mongodb://den:den@localhost:27017/customer?authSource=admin
  data:
    mongodb:
      uri: mongodb://den:den@localhost:27017/customer?authSource=admin